# Generated by Django 4.2.3 on 2023-07-06 04:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Development", "Development"),
                            ("Quality Assurance", "Quality Assurance"),
                            ("Product Management", "Product Management"),
                            (
                                "Sales/Business Development",
                                "Sales/Business Development",
                            ),
                            ("Marketing", "Marketing"),
                            ("Customer Support", "Customer Support"),
                            ("Human Resources", "Human Resources"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="employee_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employeeAPP.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Work in Progress", "Work in Progress"),
                            ("Done", "Done"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeAPP.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employeeAPP.employee",
                    ),
                ),
            ],
        ),
    ]
